title: Starry
description: >-
  Starry projects ☆

author:
  name:    starry
  twitter: starry_xp
  github:  starryyy
  instagram:  starry.xp
  email:   starry.xpp@gmail.com

baseurl: ""
url: "http://starryyy.github.io"
gh: "http://github.com/starryyy"
repository: starryyy/starryyy.github.io

defaultimage: "http://media.pixcove.com/E/1/3/Background-Contextual-Textures-Backgrounds-Soft-Bl-3318.jpg"

permalink: /:categories/:title/


# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed