title: Pixel0a
description: ""

author:
  name:    Pixel
  twitter: pixel0a
  github:  pixel0a
  email:   pixelzerg@gmail.com

baseurl: ""
url: "http://pixel0a.github.io"
gh: "http://github.com/pixel0a"

defaultimage: "/assets/images/default.jpg"

permalink: /:categories/:title/

# seo
social:
  name: Pixel
  links:
    - https://twitter.com/pixel0a
    - https://github.com/pixel0a

# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed

# collections:
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
