title: PixelZerg
description: ""

author:
  name:    PixelZerg
  twitter: pixelzerg
  github:  pixelzerg
  email:   pixelzerg@gmail.com

baseurl: ""
url: "http://pixelzerg.com"
gh: "http://github.com/pixelzerg"

# seo
social:
  name: Pixel
  links:
    - https://twitter.com/pixelzerg
    - https://github.com/pixelzerg

# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  sass_dir: res/css
  style: compressed
