title: PixelZerg
description: Hi, I'm Abhinav Bhandari and welcome to the projects of a Python/C#/JS developer, Machine Learning explorer and all-round Computer Science enthusiast!

author:
  name:    Abhinav Bhandari
  twitter: pixelzerg
  github:  pixelzerg
  email:   pixelzerg@gmail.com

baseurl: ""
url: "http://pixelzerg.github.io"
gh: "http://github.com/pixelzerg"

defaultimage: "/assets/images/default.jpg"

permalink: /:categories/:title/

# seo
social:
  name: Abhinav Bhandari
  links:
    - https://twitter.com/pixelzerg
    - https://github.com/pixelzerg

# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
