title: Starry
description: >-
  Starry projects ☆

author:
  name:    starry
  twitter: starry_xp
  github:  starryyy
  instagram:  starry.xp
  email:   starry.xp@gmail.com

baseurl: ""
url: "http://starryyy.github.io"
gh: "http://github.com/starryyy"
repository: starryyy/starryyy.github.io

permalink: /:categories/:title/


# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed