title: Pixelzery
description: ""

author:
  name:    Pixelzery
  twitter: pixelzery
  github:  pixelzery
  email:   pixelzery@gmail.com

baseurl: ""
url: "http://pixelzery.github.io"
gh: "http://github.com/pixelzery"

defaultimage: "/assets/images/default.jpg"

permalink: /:categories/:title/

# seo
social:
  name: Pixelzery
  links:
    - https://twitter.com/pixelzery
    - https://github.com/pixelzery

# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed

# collections:
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
