title: Your awesome title
email: your-email@example.com
description: >-
  Starry projects ☆.
baseurl: ""
url: "http://starryyy.github.io"
twitter_username: starry_xp
github_username:  starryyy

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed

# default excludes:
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
