title: makurell
description: >-
  Starry projects ☆

author:
  name:    makurell
  twitter: makurell
  github:  makurell
  instagram:  makurell
  email:   makureoll@gmail.com

baseurl: ""
url: "http://makurell.github.io"
gh: "http://github.com/makurell"
repository: makurell/makurell.github.io

defaultimage: "http://media.pixcove.com/E/1/3/Background-Contextual-Textures-Backgrounds-Soft-Bl-3318.jpg"

permalink: /:categories/:title/


# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed